added write transactions logs in result window
dappforce/playground pull request #14
Opened 2023-04-05 10:23 UTC by tusharojha

2023-04-05 18:05 UTC, olehmell approved these changes

2023-04-05 18:06 UTC, olehmell requested changes

2023-04-05 18:06 UTC, olehmell commented on src/playground/index.ts
>      console.log('response', response);
remove the console log

2023-04-05 18:06 UTC, olehmell commented on src/playground/index.ts
> +    response = await f(api, idToBn, (tx: any, accountId: string) => { signAndSendTx(tx, accountId, logToResponseWindow) }, IpfsContent, keyring, (r: any) => { logger(r, logToResponseWindow) }, api!.i
Can you improve the format here? Hard for read, maybe move to separated lines

2023-04-07 12:42 UTC, tusharojha commented
addd review changes.

2023-04-11 11:55 UTC, olehmell approved these changes

2023-04-11 11:55 UTC, merged